---
- name: Configure Ansible Controller
  hosts: ansible-lab-contoller
  tasks:
  - name: Ensure latest Ansible versions
    become: yes
    ansible.builtin.package:
      name: 
      - ubuntu
      - ansible
      - git
      state: latest