---
- name: Configure Ansible Controller
  become: yes
  hosts: ansible-lab-controller
  tasks:
  - name: Ensure latest Ansible versions
    become: yes
    ansible.builtin.package:
      name: 
      - ansible
      - git
      state: latest

- name: Universal host configuration
  hosts: ansible_lab_hosts
  vars:
    ansible_become: true
  roles:
  - role: ansible-hardening
    vars:
      stig_version: rhel7
      security_enable_pwquality_password_set: yes
      security_password_max_lifetime_days: 90

- name: Configure DNS server
  hosts: ansible-lab-host1
  vars:
    amsible_become: true
  tasks:
  - name: Install dnsmasq
    ansible.builtin.package:
      name: dnsmasq
      state: latest
    notify: Restart dnsmasq
  - name: Set local hostname
    become: yes
    ansible.builtin.lineinfile:
      path: /etc/hosts
      regexp: '127.0.0.1 localhost {{ansible_hostname }}'
      line: '10.1.2.4 {{ ansible_hostname }}'
    notify: Restart dnsmasq
  - name: Disable existing DNS
    ansible.builtin.service:
      name: system-resolved
      enabled: no
      state: stopped
  - name: Set dnspasq configuration file
    ansible.builtin.copy:
      src: files/dnsmasq.conf
      dest: /etc/dnsmasq.conf
      owner: root
      group: root
      mode: '0644'
    notify: Restart dnsmasq

  handlers:
  - name: Restart dnsmasq
    ansible.builtin.service:
      name: dnsmasq
      enabled: yes
      state: restarted