---
- name: Configure Ansible Controller
  become: yes
  hosts: ansible-lab-controller
  tasks:
  - name: Ensure latest Ansible versions
    become: yes
    ansible.builtin.package:
      name: 
      - ansible
      - git
      state: latest

# - name: Universal host configuration
#   become: yes
#   hosts: ansible_lab_hosts
#   tags: hardening
#   vars:
#     ansible_become: true
#   roles:
#   - role: ansible-hardening
#     vars:
#       stig_version: rhel7
#       security_enable_pwquality_password_set: yes
#       security_password_max_lifetime_days: 90

- name: Configure DNS server
  become: yes
  hosts: ansible-lab-host1
  vars:
    amsible_become: true
  tasks:
  - name: Install dnsmasq
    ansible.builtin.package:
      name: dnsmasq
      state: latest
    notify: Restart dnsmasq
  - name: Add Host1
    lineinfile:
      path: /etc/hosts
      regexp: '^10\.1\.2\.4'
      line: '10.1.2.4 DNS Server 1'
  - name: Add Host2
    lineinfile:
      path: /etc/hosts
      regexp: '^10\.1\.2\.5'
      line: '10.1.2.5 Server 2'
  - name: Add Host3
    lineinfile:
      path: /etc/hosts
      regexp: '^10\.1\.2\.6'
      line: '10.1.2.6 Server 3'
  - name: Add Controller
    lineinfile:
      path: /etc/hosts
      regexp: '^10\.1\.1\.4'
      line: '10.1.1.4 Controller'
    notify: Restart dnsmasq
  - name: Disable existing DNS
    become: yes
    ansible.builtin.service:
      name: systemd-resolved.service
      enabled: no
      state: stopped
  - name: Set dnsmasq configuration file
    ansible.builtin.copy:
      src: files/dnsmasq.conf
      dest: /etc/dnsmasq.conf
      owner: root
      group: root
      mode: '0644'
    notify: Restart dnsmasq

  handlers:
  - name: Restart dnsmasq
    ansible.builtin.service:
      name: dnsmasq
      enabled: yes
      state: restarted
  
- name: Configure hosts to use local DNS
  hosts: ansible_vms
  vars:
    ansible_become: true
  tasks:
  - name: Set resolv.conf nameserver
    lineinfile:
      path: /etc/resolv.conf
      regexp: '^nameserver'
      line: 'nameserver 10.1.2.4'

- name: Configure Samba server
  hosts: ansible-lab-host2
  vars: 
    ansible_become: true
  roles:
    - bertvv.samba