---
admin_samba_pw: '{{ vault_admin_samba_pw }}'
admin_un: 'Cipriani'

samba_server_string: 'Samba Ansible File Server'
samba_workgroup: CiprianoAndJack
samba_users:
- name: '{{ admin_un }}'
  password: '{{ admin_pw }}'
samba_shares_root: /srv/samba
samba_shares:
- name: sambashare
  comment: 'Only accessible to {{ admin_un }}'
  valid_users: '{{ admin_un }}'
  write_list: '{{ admin_un }}'
  group: '{{ admin_un }}'
  browseable: 'yes'