all:
  hosts:
    az-workstation:
      ansible_host: localhost
      ansible_connection: local
      #ansible_python_interpreter: /usr/bin/python3
  children:
    ansible-lab:
      hosts:
        ansible-lab-controller:
          ansible_host: 10.1.1.4
        
      
